# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('categorie', models.CharField(max_length=100)),
                ('nom_produit', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('fichiers', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id_projet', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('nom_projet', models.CharField(max_length=50)),
                ('etude', models.FileField(upload_to='')),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('E', 'En_etude'), ('A', 'Accepte'), ('R', 'Refuse')], default='En_etude', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('type_user', models.CharField(choices=[('AD', 'Admin'), ('CL', 'Client')], default='Client', max_length=10)),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cin', models.IntegerField()),
            ],
        ),
    ]
