# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='nom_categorie',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='fichiers',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
