# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteq', '0002_auto_20170528_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='etude',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
