# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soteq', '0003_auto_20170528_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='fichiers',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projet',
            name='etude',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
