# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import soteq.models


class Migration(migrations.Migration):

    dependencies = [
        ('soteq', '0004_auto_20170528_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='images',
            field=models.ImageField(upload_to=soteq.models.upload_location),
        ),
    ]
