# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import soteq.models


class Migration(migrations.Migration):

    dependencies = [
        ('soteq', '0005_auto_20170529_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='images1',
            field=models.ImageField(blank=True, null=True, upload_to=soteq.models.upload_location),
        ),
        migrations.AddField(
            model_name='produit',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to=soteq.models.upload_location),
        ),
        migrations.AddField(
            model_name='produit',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to=soteq.models.upload_location),
        ),
        migrations.AddField(
            model_name='produit',
            name='images4',
            field=models.ImageField(blank=True, null=True, upload_to=soteq.models.upload_location),
        ),
    ]
