# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soteq', '0006_auto_20170531_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='images',
            new_name='images0',
        ),
    ]
