from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(r'^$', views.index_view.as_view()),
    url(r'^index', views.index_view.as_view(), name="index"),
    url(r'^contact', views.contact_view.as_view(), name='contact'),
    url(r'^projects', views.project_view.as_view(), name='projet'),
    url(r'^produits', views.produits_view.as_view(), name='produits'),
    url(r'^SAV', views.SAV_view.as_view(), name='SAV'),
    url(r'^prod/(?P<id>\d+)/$', views.produit_detail_view.as_view(), name='detail'),
    url(r'^signup/$', views.signup.as_view(), name='signup'),
    url(r'^search/$', views.search_view.as_view(), name='search'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^story_1', views.story_view_1.as_view(), name="story_1"),
    url(r'^story_2', views.story_view_2.as_view(), name="story_2"),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    # views.activate, name='activate'),
    # url(r'^prod/(?P<id>\d+)/$', produit_1, name='detail'),

    # url(r'^prod/1/$', views.produit_detail_view.as_view(), kwargs={'id': 1}, name='detail_1'),
    # url(r'^prod/2/$', views.produit_detail_view.as_view(), kwargs={'id': 2}, name='detail_2'),
    # url(r'^prod/3/$', views.produit_detail_view.as_view(), kwargs={'id': 3}, name='detail_3'),
    # url(r'^prod/4/$', views.produit_detail_view.as_view(), kwargs={'id': 4}, name='detail_4'),
    # url(r'^prod/5/$', views.produit_detail_view.as_view(), kwargs={'id': 5}, name='detail_5'),
    # url(r'^prod/6/$', views.produit_detail_view.as_view(), kwargs={'id': 6}, name='detail_6'),
    # url(r'^prod/7/$', views.produit_detail_view.as_view(), kwargs={'id': 7}, name='detail_7'),
    # url(r'^prod/8/$', views.produit_detail_view.as_view(), kwargs={'id': 8}, name='detail_8'),
    # url(r'^prod/9/$', views.produit_detail_view.as_view(), kwargs={'id': 9}, name='detail_9'),
    # url(r'^prod/10/$', views.produit_detail_view.as_view(), kwargs={'id': 10}, name='detail_10'),
    # url(r'^prod/11/$', views.produit_detail_view.as_view(), kwargs={'id': 11}, name='detail_11'),
    # url(r'^prod/12/$', views.produit_detail_view.as_view(), kwargs={'id': 12}, name='detail_12'),
    # url(r'^prod/13/$', views.produit_detail_view.as_view(), kwargs={'id': 13}, name='detail_13'),
    # url(r'^prod/14/$', views.produit_detail_view.as_view(), kwargs={'id': 14}, name='detail_14'),
    # url(r'^prod/15/$', views.produit_detail_view.as_view(), kwargs={'id': 15}, name='detail_15'),
    # url(r'^prod/16/$', views.produit_detail_view.as_view(), kwargs={'id': 16}, name='detail_16'),
    # url(r'^prod/17/$', views.produit_detail_view.as_view(), kwargs={'id': 17}, name='detail_17'),
    # url(r'^prod/18/$', views.produit_detail_view.as_view(), kwargs={'id': 18}, name='detail_18'),
    # url(r'^prod/19/$', views.produit_detail_view.as_view(), kwargs={'id': 19}, name='detail_19'),
    # url(r'^prod/20/$', views.produit_detail_view.as_view(), kwargs={'id': 20}, name='detail_20'),
    # url(r'^prod/21/$', views.produit_detail_view.as_view(), kwargs={'id': 21}, name='detail_21'),
    # url(r'^prod/22/$', views.produit_detail_view.as_view(), kwargs={'id': 22}, name='detail_22'),
    # url(r'^prod/23/$', views.produit_detail_view.as_view(), kwargs={'id': 23}, name='detail_23'),
    # url(r'^prod/24/$', views.produit_detail_view.as_view(), kwargs={'id': 24}, name='detail_24'),
    # url(r'^prod/25/$', views.produit_detail_view.as_view(), kwargs={'id': 25}, name='detail_25'),
    # url(r'^prod/26/$', views.produit_detail_view.as_view(), kwargs={'id': 26}, name='detail_26'),
    # url(r'^prod/27/$', views.produit_detail_view.as_view(), kwargs={'id': 27}, name='detail_27'),
    # url(r'^prod/28/$', views.produit_detail_view.as_view(), kwargs={'id': 28}, name='detail_28'),
    # url(r'^prod/29/$', views.produit_detail_view.as_view(), kwargs={'id': 29}, name='detail_29'),
    # url(r'^prod/30/$', views.produit_detail_view.as_view(), kwargs={'id': 30}, name='detail_30'),

]
